import csv
import os
from typing import Any, Dict
from app.config import settings

try:
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle
    HAS_REPORTLAB = True
except ImportError:
    HAS_REPORTLAB = False


def generate_report_files(workflow_id: str, run_data: Dict[str, Any]) -> Dict[str, Any]:
    """
    Generates a PDF disaster report and CSV export from workflow run data.
    """
    pdf_filename = f"disaster_report_{workflow_id}.pdf"
    csv_filename = f"critical_nodes_{workflow_id}.csv"

    pdf_path = os.path.join(settings.REPORTS_DIR, pdf_filename)
    csv_path = os.path.join(settings.REPORTS_DIR, csv_filename)

    hazard_type = run_data.get("hazard_type", "FLOOD")
    sim_data = run_data.get("simulation_data") or {}
    crit_nodes = run_data.get("critical_nodes") or []
    plan_data = run_data.get("planning_data") or {}

    resilience = sim_data.get("resilience", 1.0)
    travel_delay = sim_data.get("travel_delay", 0.0)
    affected_regions = sim_data.get("affected_regions", [])
    evacuation_routes = plan_data.get("evacuation_routes", [])
    repair_priorities = plan_data.get("repair_priority", [])
    recommendations = plan_data.get("recommendations", [])

    summary_text = (
        f"Following the simulated <b>{hazard_type}</b> disaster event, topological graph network analysis "
        f"evaluated transport resilience at <b>{int(resilience * 100)}%</b>. Major bottlenecks created an average "
        f"travel delay increase of <b>+{travel_delay}%</b> across critical arterial routes."
    )

    # 1. Build CSV Export
    with open(csv_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["Type", "Node ID", "Latitude", "Longitude", "Criticality Score", "Bridge Adjacent", "Priority/ETA", "Details"])
        for cn in crit_nodes:
            writer.writerow([
                "Critical Node",
                cn.get("node_id"),
                cn.get("lat"),
                cn.get("lon"),
                cn.get("criticality_score"),
                cn.get("is_bridge_adjacent"),
                "-",
                f"Betweenness: {cn.get('betweenness')}, Closeness: {cn.get('closeness')}"
            ])
        for er in evacuation_routes:
            writer.writerow([
                "Evacuation Route",
                er.get("from_node"),
                "-",
                "-",
                "-",
                "-",
                f"ETA: {er.get('eta_min')}m",
                f"To: {er.get('to_node')}, Vehicle: {er.get('vehicle')}"
            ])

    # 2. Build PDF Document
    if HAS_REPORTLAB:
        doc = SimpleDocTemplate(pdf_path, pagesize=letter, rightMargin=36, leftMargin=36, topMargin=36, bottomMargin=36)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            "ReportTitle",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=20,
            leading=24,
            textColor=colors.HexColor("#3b0764"),
        )
        h2_style = ParagraphStyle(
            "ReportH2",
            parent=styles["Heading2"],
            fontName="Helvetica-Bold",
            fontSize=13,
            leading=16,
            textColor=colors.HexColor("#6b21a8"),
            spaceBefore=10,
            spaceAfter=4,
        )
        body_style = ParagraphStyle(
            "ReportBody",
            parent=styles["BodyText"],
            fontName="Helvetica",
            fontSize=9,
            leading=12,
            textColor=colors.HexColor("#1e293b"),
        )

        story = []

        story.append(Paragraph(f"Disaster Resilience & Logistics Report: {hazard_type}", title_style))
        story.append(Paragraph(f"Workflow ID: {workflow_id} | Generated by KRATOS Intelligence Platform", body_style))
        story.append(Spacer(1, 10))
        story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor("#9333ea"), spaceAfter=12))

        metrics_data = [
            ["Resilience Index", "Travel Delay Penalty", "Affected Sectors", "Evacuation Routes"],
            [f"{int(resilience * 100)}%", f"+{travel_delay}%", f"{len(affected_regions)}", f"{len(evacuation_routes)}"],
        ]
        t_metrics = Table(metrics_data, colWidths=[130, 130, 130, 130])
        t_metrics.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f3e8ff")),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor("#581c87")),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica-Bold'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('FONTSIZE', (0, 1), (-1, 1), 14),
            ('TEXTCOLOR', (0, 1), (-1, 1), colors.HexColor("#1e1b4b")),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#d8b4fe")),
        ]))
        story.append(t_metrics)
        story.append(Spacer(1, 14))

        story.append(Paragraph("1. Executive Summary", h2_style))
        story.append(Paragraph(summary_text, body_style))
        story.append(Spacer(1, 10))

        story.append(Paragraph("2. Top Critical Network Nodes", h2_style))
        if crit_nodes:
            cn_table_data = [["Node ID", "Latitude", "Longitude", "Score", "Bridge Status"]]
            for cn in crit_nodes[:6]:
                cn_table_data.append([
                    str(cn.get("node_id")),
                    str(cn.get("lat")),
                    str(cn.get("lon")),
                    str(cn.get("criticality_score")),
                    "YES" if cn.get("is_bridge_adjacent") else "NO",
                ])
            t_cn = Table(cn_table_data, colWidths=[100, 100, 100, 100, 120])
            t_cn.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#6b21a8")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 8),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#cbd5e1")),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
            ]))
            story.append(t_cn)
        else:
            story.append(Paragraph("No critical node details recorded.", body_style))
        story.append(Spacer(1, 10))

        story.append(Paragraph("3. Recommended Evacuation & Repair Plan", h2_style))
        if recommendations:
            for rec in recommendations:
                story.append(Paragraph(f"• {rec}", body_style))
                story.append(Spacer(1, 3))
        else:
            story.append(Paragraph("No specific recommendations generated.", body_style))

        doc.build(story)
    else:
        # Graceful text report fallback if reportlab library not installed in environment
        with open(pdf_path, "w", encoding="utf-8") as f:
            f.write(f"=== Disaster Resilience Report: {hazard_type} ===\n")
            f.write(f"Workflow ID: {workflow_id}\n")
            f.write(f"Resilience Score: {int(resilience * 100)}%\n")
            f.write(f"Travel Delay: +{travel_delay}%\n\n")
            f.write("Executive Summary:\n" + summary_text.replace("<b>", "").replace("</b>", "") + "\n\n")
            f.write("Recommendations:\n")
            for rec in recommendations:
                f.write(f"- {rec}\n")

    return {
        "pdf_path": pdf_path,
        "csv_path": csv_path,
        "pdf_url": f"/reports/{pdf_filename}",
        "csv_url": f"/reports/{csv_filename}",
        "executive_summary": summary_text,
        "risk_analysis": f"Resilience score drops to {int(resilience * 100)}% with travel delay penalty +{travel_delay}%.",
        "repair_narrative": f"Focus initial repair effort on top node {repair_priorities[0].get('node_id') if repair_priorities else 'N/A'}.",
        "recommendations": recommendations,
    }
